### PR TITLE
fix 'show tags' query

### LINKED ISSUE #42: Cannot query "show tags"
Trying to query:
```
try (Connection connection = dataSource.getConnection()) {
     Statement statement = connection.createStatement();
     ResultSet res = statement.executeQuery( "show tags" );
 }
```
results in error:
`java.sql.SQLException: Method executeQuery() can only execute nGql to query data, but the current nGql do not contains any query keyword in [match, lookup, go, fetch, find, subgraph], please modify your nGql or use executeUpdate(), execute().`

"execute()" and "executeUpdate()" don't return query results

Similar for other show/describe statements

### LINKED ISSUE #56: Cannot query 'show tags'
```
Caused by: java.sql.SQLException: Method executeQuery() can only execute nGql to query data, but the current nGql do not contains any query keyword in [match, lookup, go, fetch, find, subgraph], please modify your nGql or use executeUpdate(), execute().
	at com.vesoft.nebula.jdbc.statement.NebulaStatementImpl.checkReadOnly(NebulaStatementImpl.java:97)
	at com.vesoft.nebula.jdbc.statement.NebulaPreparedStatementImpl.executeQuery(NebulaPreparedStatementImpl.java:44)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:722)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)
```

### PR DESCRIPTION
**Pull request by cdalexndr**
closes #42

### CODE REVIEW

File: src/main/java/com/vesoft/nebula/jdbc/statement/NebulaStatementImpl.java [hunk 1]
```diff
@@ -19,7 +19,7 @@
 public class NebulaStatementImpl implements NebulaStatement {
     protected final Logger log = LoggerFactory.getLogger(this.getClass());
     protected final String[] updateKeyword = {"update", "delete", "insert", "upsert", "create", "drop", "alter", "rebuild"};
-    protected final String[] queryKeyword = {"match", "lookup", "go", "fetch", "find", "subgraph"};
+    protected final String[] queryKeyword = {"match", "lookup", "go", "fetch", "find", "subgraph", "show"};
```
Comment (wey-gu) [inline src/main/java/com/vesoft/nebula/jdbc/statement/NebulaStatementImpl.java]: Could you please also add `desc` and `describe`

Comment (Young-Flash) [reply src/main/java/com/vesoft/nebula/jdbc/statement/NebulaStatementImpl.java]: could you plz help add the two keyword above and resolve the conflict?

**Comment by wey-gu** [comment]
@Young-Flash I fixed above issues, if it's good we could merge :D

**Review by wey-gu — APPROVED** [review]
