### PR TITLE
fix exception when calling getWarnings

### LINKED ISSUE #54: Method getWarnings in class com.vesoft.nebula.jdbc.statement.NebulaStatementImpl is not supported.
Using spring-jdbc, JdbcTemplate always calls Statement.getWarnings(), and because this method is not implemented, it results in exception.
https://github.com/spring-projects/spring-framework/blob/main/spring-jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java#L1500 

Example call stack:
```
buildUnsupportedOperationException:26, ExceptionBuilder (com.vesoft.nebula.jdbc.utils)
getWarnings:208, NebulaStatementImpl (com.vesoft.nebula.jdbc.statement)
handleWarnings:1506, JdbcTemplate (org.springframework.jdbc.core)
execute:652, JdbcTemplate (org.springframework.jdbc.core)
query:713, JdbcTemplate (org.springframework.jdbc.core)
```

### PR DESCRIPTION
**Pull request by cdalexndr**
Return no sql warnings.

closes #54

### CODE REVIEW

File: src/main/java/com/vesoft/nebula/jdbc/statement/NebulaStatementImpl.java [hunk 1]
```diff
@@ -204,8 +204,8 @@ public void cancel() throws SQLException {
     }
 
     @Override
-    public SQLWarning getWarnings() throws SQLException {
-        throw ExceptionBuilder.buildUnsupportedOperationException();
+    public SQLWarning getWarnings() {
+        return null;
```
Comment (Young-Flash) [inline src/main/java/com/vesoft/nebula/jdbc/statement/NebulaStatementImpl.java:208]: could you explain why always return `null` here?

Comment (Joy-Panda) [reply src/main/java/com/vesoft/nebula/jdbc/statement/NebulaStatementImpl.java:208]: This issue answers the question very well #54.
Clickhouse jdbc client is also written in this way and returns null

https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseStatementImpl.java
line 628

Comment (Young-Flash) [reply src/main/java/com/vesoft/nebula/jdbc/statement/NebulaStatementImpl.java:208]: Directly returning `null` may not be the best approach. It would be better if we could return `SQLWarning`. I'd like to merge this PR first. How do you think, @wey-gu?

Thank you for your contribution.
